{
 "title": "Ping Statistics",
 "description": "Data visualization for https://github.com/jheddings/pingdat",
 "tags": [
  "network",
  "performance"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(ping_requests_total, instance)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "label_values(ping_requests_total{instance=~\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Response Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_reponse_time{name=~\"$target\", instance=~\"$instance\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (le) (increase(ping_observations_bucket{name=~\"$target\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ping_reponse_time{name=~\"$target\", instance=~\"$instance\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Timeout Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ping_errors_total{name=~\"$target\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ping_errors_total{name=~\"$target\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Combined Response Times",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "ping_reponse_time", "legendFormat": "{{address}}" }
   ]
  }
 ]
}