---
name: Unit Tests

"on":

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Setup uv w/ python-${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: uv sync --all-extras

      - name: Run unit tests
        run: uv run pytest -m "not network" tests/
